### ISSUE TITLE
what kind of back end server do you use?

### ISSUE THREAD

**Issue by Alvinzhao** [hletrd/neural_style#1]
good job! I would like to know what kind of back end server can run this app? Thanks!

**Comment by hletrd** [comment]
I used CentOS 7 for server.

**Comment by Deepak-** [comment]
@hletrd What kind of GPU do you use for processing?

**Comment by hletrd** [comment]
I don't use GPU computing now, and that's why the service is very slow.
All computations are taking place in i5-4460 CPU.

**Comment by Deepak-** [comment]
@hletrd I see, thank you!
